#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Scaffolding of this wizard:
#   O Sentry já está integrado no código (CEPT2-9): src/api/common/sentry.ts,
#   init em src/api/main.ts, captureException no AllExceptionsFilter. O que
#   falta é SÓ o DSN no .env do VPS + reiniciar. O .env remoto é lido por
#   bancada-api E bancada-sync-worker via env_file no docker-compose.yml.
#   (Confirmado 2026-09-17: sem nenhuma SENTRY_* no VPS hoje.)
SSH_HOST="${SSH_HOST:-narniano@167.233.254.53}"
REMOTE_ENV="${REMOTE_ENV:-/opt/a-bancada-evangelica/.env}"
COMPOSE_DIR="${COMPOSE_DIR:-/home/narniano/hetzner-infra/bancada}"

# _ssh runs a command on the VPS (BatchMode: no password prompt).
_ssh() {
  ssh -o ConnectTimeout=10 -o BatchMode=yes "$SSH_HOST" "$@"
}

# _remote_has KEY: true if KEY= exists in the remote .env.
_remote_has() {
  _ssh "grep -qE '^${1}=' '$REMOTE_ENV'" 2>/dev/null
}

# _write_remote_env KEY VALUE upserts KEY=VALUE into the remote .env (the one
# the docker containers read). Avoids a local .env entirely — that file is
# explicitly a frozen dev copy, NOT production (see warning at its top).
_write_remote_env() {
  local key="$1" value="$2"
  _ssh "grep -vE '^${key}=' '$REMOTE_ENV' > '$REMOTE_ENV.tmp' ; echo '${key}=${value}' >> '$REMOTE_ENV.tmp' ; mv '$REMOTE_ENV.tmp' '$REMOTE_ENV'"
  note "✓ wrote $key → $REMOTE_ENV (VPS)"
}

TOTAL_STAGES=4

banner "Sentry: ativar monitoramento de erros da API"

# ── Stage 1: Sentry project + DSN ────────────────────────────────────────────
stage "Sentry: criar projeto + copiar o DSN"
say "Vamos criar (ou reutilizar) o projeto do Sentry e pegar o DSN."
say "O Sentry está integrado no código há dias (CEPT2-9) — só falta este DSN."
open_url "https://sentry.io/organizations/+/projects/new/"
step "Se não houver org ainda, crie uma (grupo livre é o suficiente)."
step "Em 'Choose your platform', escolha 'Node.js' (o SDK é @sentry/node, NestJS roda em cima disso)."
step "Em 'Set your default alert settings' pode deixar padrão. Nome do projeto: a-bancada-evangelica"
step "Clique 'Create Project'."
step "Na tela de boas-vindas ou em: Settings → Projects → a-bancada-evangelica → Client Keys (DSN)"
step "Copie o valor da linha 'DSN' — começa com https:// e termina em ingest.sentry.io/..."
warn "Se já existir um projeto, pode reutilizar; o DSN é o mesmo conceito."
ask_secret SENTRY_DSN "Cole o DSN completo (https://...ingest.sentry.io/...):"
if [[ "$SENTRY_DSN" != https://* ]]; then
  warn "isso não parece um DSN (esperava https://...) — confira e cole de novo."
  ask_secret SENTRY_DSN "Cole o DSN completo novamente:"
fi
note "DSN capturado (${#SENTRY_DSN} caracteres)."

# ── Stage 2: aplicar no VPS + release opcional ────────────────────────────────
stage "VPS: gravar SENTRY_DSN no .env remoto"
say "Vou gravar as variáveis no .env que a API lê ($REMOTE_ENV)."
if ! _ssh "touch '$REMOTE_ENV'" 2>/dev/null; then
  warn "Não consegui conectar/gravar em $SSH_HOST. Confirme: ssh $SSH_HOST funciona?"
  pause "Identifique o problema e pressione Enter para tentar de novo."
fi
_write_remote_env "SENTRY_DSN" "$SENTRY_DSN"
note "SENTRY_RELEASE identifica o deploy (aparece no Sentry). Recomendo o SHA do repo:"
RELEASE_DEFAULT=$(git -C "$(dirname "$0")/.." rev-parse --short HEAD 2>/dev/null || echo dc83d25)
ask SENTRY_RELEASE "SENTRY_RELEASE (opcional, formato livre): [${RELEASE_DEFAULT}]"
SENTRY_RELEASE="${SENTRY_RELEASE:-$RELEASE_DEFAULT}"
_write_remote_env "SENTRY_RELEASE" "$SENTRY_RELEASE"
note "Reiniciando a API é o próximo estágio — o compose relê o env_file ao recriar."

# ── Stage 3: restart API + verificação ────────────────────────────────────────
stage "VPS: reiniciar a API e confirmar o Sentry ativo"
say "Vou recriar o bancada-api (env_file muda → precisa recreate, não só restart)."
step "Comando executado: cd $COMPOSE_DIR && docker compose up -d --no-deps --no-build bancada-api"
CONTAINER_FRESH=0
if _ssh "cd '$COMPOSE_DIR' && docker compose up -d --no-deps --no-build bancada-api"; then
  CONTAINER_FRESH=1
  note "docker compose up deparou OK no VPS."
else
  warn "docker compose up falhou. Revise manualmente."
  pause "Corrija no VPS e pressione Enter."
fi
if [[ "$CONTAINER_FRESH" -eq 1 ]]; then
  step "Aguardando o healthcheck da API (até ~30s)."
  sleep 20
  curl -sf -o /dev/null -w '  health: %{http_code}\n' https://api-bancada.narniano.com/health || warn "health ainda não respondeu — pode estar no tempo de start_period"
fi
say "COMO CONFIRMAR de verdade: o log do container deve dizer 'Sentry ativo'."
step "ssh $SSH_HOST → docker logs --tail 50 bancada-api | grep -i sentry"
if _ssh "docker logs --tail 60 bancada-api | grep -iE 'sentry' | tail -3"; then
  note "✓ log do Sentry presente no container."
else
  warn "Não achei 'Sentry' no log recente. Verifique: o deploy do dc83d25 (com sentry.ts) está no VPS?"
fi

# ── Stage 4: persistir no GitHub + ROADMAP ────────────────────────────────────
stage "GitHub secret + ROADMAP"
say "Guardo o DSN também como secret do GitHub (caso um job de CI precise depois)."
set_secret SENTRY_DSN "$SENTRY_DSN"
say "Marcando CEPT2-9 como aplicado no ROADMAP."
ROADMAP_FILE=$(cd "$(dirname "$0")/.." && pwd)/ROADMAP.md
if [[ -f "$ROADMAP_FILE" ]]; then
  sed -i 's|- \[x\] \*\*CEPT2-9 · Sentry\*\* — decisão do Rilson: ATIVAR (2026-09-16).|- [x] **CEPT2-9 · Sentry** — decisão do Rilson: ATIVAR (2026-09-16). **APLICADO via wizard 2026-09-17 (SENTRY_DSN no VPS).**|' "$ROADMAP_FILE"
  note "✓ ROADMAP marcado."
else
  warn "ROADMAP.md não encontrado em $ROADMAP_FILE — marque manualmente."
fi

finish
say "Próximos passos: (1) commit do ROADMAP + deste wizard; (2) push → o Deploy VPS ignora (sem mudança de código), mas o commit documenta."